stages:
  - mirror
  - publish

mirror:
  stage: mirror
  script:
    - setsid ./ci/mirror.sh
  only:
    - /^(main.*)$/
  tags:
    - veggieoss

build-img:
  stage: publish
  script:
    - setsid ./ci/docker-deliver.sh "humidity-and-temperature" "1.0"
  only:
    refs:
      - /^(main.*)$/
    changes:
      - src/*
      - Dockerfile
      - docker-compose-build-arm.yml
      - ci/docker-deliver.sh
      - .gitlab-ci.yml
  tags:
    - buildarm
